# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rubycraft}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Ribeiro"]
  s.date = %q{2011-08-03}
  s.description = %q{It allows you to change all the
blocks in region files in whatever way you see fit. Example: http://bit.ly/r62qGo}
  s.email = %q{danrbr@gmail.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/block.rb",
    "lib/block_type.rb",
    "lib/byte_converter.rb",
    "lib/chunk.rb",
    "lib/matrix3d.rb",
    "lib/nbt_helper.rb",
    "lib/region.rb"
  ]
  s.homepage = %q{http://github.com/danielribeiro/RubyCraft}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Lib for manipualting Minecraft world files}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nbtfile>, [">= 0.2.0"])
    else
      s.add_dependency(%q<nbtfile>, [">= 0.2.0"])
    end
  else
    s.add_dependency(%q<nbtfile>, [">= 0.2.0"])
  end
end

